import Head from "next/head";
import PageComponent from "../component/PageComponent";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>CSV File Viewer</title>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
            integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
            crossOrigin="anonymous"
          />
          <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
            crossOrigin="anonymous"
          />
          <link
            rel="stylesheet"
            href="https://www.w3schools.com/w3css/4/w3.css"
          />
        </Head>

        <main className={styles.main}>
          <PageComponent />
        </main>

        <footer className={styles.footer}>
          <script
            src="https://unpkg.com/react/umd/react.production.min.js"
            crossOrigin="anonymous"
          ></script>
          <script
            src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"
            crossOrigin="anonymous"
          ></script>
          <script
            src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"
            crossOrigin="anonymous"
          ></script>
        </footer>
      </div>
    </>
  );
}
